import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/modules/Menu";
import Footer from "@/modules/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Piadrol.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" bg-black  ">
          <Menu  />
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
